//
//  CircularMeterTesting.swift
//  SparkComponentCircularMeter
//
//  Created by robin.lemaire on 27/05/2026.
//  Copyright © 2026 Leboncoin. All rights reserved.
//

import Foundation

// TODO: remove this file if there is a file no generated by sourcery !

// IMPORTANT
// This file is needed because there is
// no code (without the code generated
// by sourcery) on this target.

